services:
  backend:
    image: backend
    init: true
    ports:
      - 80
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./cgi-bin:/www/cgi-bin

  coffee:
    image: lunch:v7
    build: .
    environment:
      - TITLE=${TITLE:-Welcome}
      - COLOR=${COLOR:-gray}
      - BODY=${BODY:-please use TITLE/COLOR/BODY env vars}
    labels:
      - traefik.frontend.auth.basic=admin:$$1$$I5Kt8BwT$$G4y6mBV3xVzyZKUECxqV61
    ports:
      - 80
  
  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - vipdb:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
  
  adminer:
    image: adminer
    ports:
    - 8080

volumes:
  vipdb:

networks:
  default:
    name: proxy