services:
  proxy:
    image: nginxproxy/nginx-proxy:1.4
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  coffee:
    image: lunch:v7
    build: .
    environment:
      - TITLE=${TITLE:-Welcome}
      - COLOR=${COLOR:-gray}
      - BODY=${BODY:-please use TITLE/COLOR/BODY env vars}
      - VIRTUAL_HOST=coffee.lvh.me
    ports:
      - 80
  
  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - vipdb:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
  
  adminer:
    image: adminer
    ports:
    - 8080

volumes:
  vipdb:
  