services:
  coffee:
    image: lunch:v7
    build: .
    environment:
      - TITLE=${TITLE:-Welcome}
      - COLOR=${COLOR:-gray}
      - BODY=${BODY:-please use TITLE/COLOR/BODY env vars}
    ports:
      - 80
  
  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - vipdb:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
  
  adminer:
    image: adminer
    ports:
    - 8080

volumes:
  vipdb:
  